logging:
  level:
    root: INFO

aws:
  sns:
    region: ap-northeast-2
    endpoint: http://localhost:4566
    credentials:
      access-key: test
      secret-key: test
    topics:
      # LocalStackTestContainer.register()에서 주입한 키와 맞춤
      board-reply: arn:aws:sns:ap-northeast-2:000000000000:local-board-reply-sns

  sqs:
    region: ap-northeast-2
    endpoint: http://localhost:4566
    credentials:
      access-key: test
      secret-key: test
    queues:
      # LocalStackTestContainer.register()에서 주입한 키와 맞춤
      post-notify: http://sqs.ap-northeast-2.localhost.localstack.cloud:4566/000000000000/local-board-post-notify-sqs
      reply-action: http://sqs.ap-northeast-2.localhost.localstack.cloud:4566/000000000000/local-board-reply-action-sqs

spring:
  datasource:
    url: jdbc:mysql://localhost:33060/tikim_local?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    encoding: UTF-8

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

redisson:
  host: localhost
  port: 63790
  password:
  timeout: 3000
  use-ssl: false
